---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
      os_environment:
        - key: TYPEORM_PORT
          value: 5432
        - key: TYPEORM_CONNECTION
          value: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
        - key: TYPEORM_ENTITIES
          value: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
        - key: TYPEORM_USERNAME
          value: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
        - key: TYPEORM_PASSWORD
          value: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
        - key: TYPEORM_DATABASE
          value: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
        - key: TYPEORM_HOST
          value: "{{ lookup('env', 'TYPEORM_HOST')}}"
        - key: TYPEORM_MIGRATIONS_DIR
          value: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
        - key: TYPEORM_MIGRATIONS
          value: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"


  tasks:
    - name: "install python for Ansible."
      apt:
        name: python3
        state: latest
        update_cache: true

    - name: "add os environment variables"
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ os_environment }}"
  roles:
    - configure-server

