version: 2.1


# Use a package of configuration called an orb.
orbs:
# Choose either one of the orbs below
# welcome: circleci/welcome-orb@0.4.1
# aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project


commands:
  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            # Your code here
            exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend